# Generated by Django 5.2.18 on 2026-10-08 03:26

from django.db import migrations, models


def copy_teacher_name(apps, schema_editor):
    """Teacher FK o'chirilishidan oldin uning ismini matn maydoniga ko'chirish."""
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.select_related("teacher").only(
        "pk", "teacher__first_name", "teacher__last_name"
    ):
        name = f"{course.teacher.first_name} {course.teacher.last_name}".strip()
        if name:
            Course.objects.filter(pk=course.pk).update(instructor_name=name[:150])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(copy_teacher_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
