# Generated by Django 5.2.18 on 2026-10-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_teacher_course_instructor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
