# Generated by Django 5.2.18 on 2026-10-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_video_id_255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover',
        ),
        migrations.AddField(
            model_name='course',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(blank=True, help_text="Share → Anyone with the link → havolani to'liq yopishtiring", max_length=255, verbose_name='Video (Google Drive havolasi)'),
        ),
    ]
