# Generated by Django 5.2.18 on 2026-10-08 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def published_are_approved(apps, schema_editor):
    """Mavjud nashr qilingan (admin) kurslar — tasdiqlangan."""
    Course = apps.get_model("courses", "Course")
    Course.objects.filter(is_published=True).update(review_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_cover_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="Teacher. Bo'sh — platforma (admin) kursi", limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='review_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Admin izohi'),
        ),
        migrations.AddField(
            model_name='course',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Tekshiruvda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Qaytarilgan')], db_index=True, default='draft', max_length=10),
        ),
        migrations.RunPython(published_are_approved, migrations.RunPython.noop),
    ]
