# Generated by Django 5.2.18 on 2026-10-08 03:26

from django.db import migrations, models


def teachers_to_students(apps, schema_editor):
    """Teacher roli olib tashlandi: mavjud teacher'lar student bo'ladi va Django Admin'ga kira olmaydi."""
    User = apps.get_model("users", "User")
    User.objects.filter(role="teacher").update(role="student")
    User.objects.filter(is_staff=True, is_superuser=False).exclude(role="admin").update(
        is_staff=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        # teacher FK avval o'chirilsin (courses.0002 ismni ko'chiradi)
        ('courses', '0002_remove_course_teacher_course_instructor_name'),
    ]

    operations = [
        migrations.RunPython(teachers_to_students, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Ota-ona'), ('admin', 'Admin')], db_index=True, default='student', max_length=10),
        ),
    ]
